### ISSUE TITLE
FLOCK2 docker image

### ISSUE THREAD

**Issue by appie-17** [clydemcqueen/flock2#32]
Thanks alot for your effort in making this ROS2 package for the Tello drone! Since I'm still using ROS1 on a daily basis, I decided to create a docker image in order to run all your ROS2 packages. The image can be found at https://hub.docker.com/r/jordyvanappeven/flock2, while using the following script to run the docker image:
```
#!/bin/bash
FLOCK2_WS=/home/jordy/flock2_ws ### CHANGE TO FLOCK2_WS DIRECOTRY
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run -it \
           --volume=$XSOCK:$XSOCK:rw \
           --volume=$XAUTH:$XAUTH:rw \
           --volume=$FLOCK2_WS:/home/ros/flock2_ws:rw \
           --volume=/dev/input:/dev/input:rw \
           --privileged \
           --env="XAUTHORITY=${XAUTH}" \
           --env="DISPLAY" \
           --env="QT_11_NO_MITSHM=1" \
           --env="UID=`id -u $who`" \
           --env="UID=`id -g $who`" \
           --net host \
           --name flock2 \
       jordyvanappeven/flock2:tello \
       bash
```
Just make sure to change the `FLOCK2_WS` variable to the appropriate directory, while clone all required packages to the `src` folder. After running the docker navigate to the flock2_ws folder and build the ROS2 package `colcon build --event-handlers console_direct+`. Then source the package `source install/setup.bash` and don't forget to export the Tello models for Gazebo by:
```
export GAZEBO_MODEL_PATH=${PWD}/install/tello_gazebo/share/tello_gazebo/models
source /usr/share/gazebo/setup.sh
```

**Comment by clydemcqueen** [comment]
Nice, thanks for the contribution.
