### ISSUE TITLE
launch files refer to older vlam node names

### ISSUE THREAD

**Issue by imsuneaik** [clydemcqueen/flock2#39]
I have been following the all your provided steps to install flock2. 

> mkdir -p ~/flock2_ws/src
cd ~/flock2_ws/src
git clone https://github.com/clydemcqueen/flock2.git
git clone https://github.com/ptrmu/fiducial_vlam.git
git clone https://github.com/clydemcqueen/tello_ros.git
cd ..
source /opt/ros/eloquent/setup.bash
If you didn't install Gazebo, avoid building tello_gazebo:
colcon build --event-handlers console_direct+ --packages-skip tello_gazebo
> 

Upon the last instruction of the Step 4. I faced an error shown below. 

~/flock2_ws$ colcon build --event-handlers console_direct+
[0.542s] ERROR:colcon:colcon build: Duplicate package names not supported:
- tello_description:
  - src/tello_ros/tello_description
  - tello_ros/tello_description
- tello_driver:
  - src/tello_ros/tello_driver
  - tello_ros/tello_driver
- tello_gazebo:
  - src/tello_ros/tello_gazebo
  - tello_ros/tello_gazebo
- tello_msgs:
  - src/tello_ros/tello_msgs
  - tello_ros/tello_msgs

**Comment by clydemcqueen** [comment]
It looks like you have 2 copies of the 'tello_ros' directory. The only copy should be in '~/flock2_ws/src'.

**Comment by imsuneaik** [comment]
Thanks for the swift answer. I have managed to fix that like ur solution stated above. However, it get another error as shown below. 

> flock2
CMake Error at CMakeLists.txt:49 (find_package):
  By not providing "Findtello_msgs.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "tello_msgs", but CMake did not find one.
  Could not find a package configuration file provided by "tello_msgs" with
  any of the following names:
    tello_msgsConfig.cmake
    tello_msgs-config.cmake
  Add the installation prefix of "tello_msgs" to CMAKE_PREFIX_PATH or set
  "tello_msgs_DIR" to a directory containing one of the above files.  If
  "tello_msgs" provides a separate development package or SDK, be sure it has
  been installed.>

Please advice and thank you for the help.

**Comment by clydemcqueen** [comment]
That's strange. You may want to delete the workspace and start over.

ROS2 has some nice tutorials: https://index.ros.org/doc/ros2/Tutorials/Workspace/Creating-A-Workspace/

**Comment by imsuneaik** [comment]
Thank you. I have managed to delete and recreating the workspace building was fine as well.. However, when I am trying to run launch_one.py, I would face some error message. `[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'vmap_node' not found on the libexec directory '/home/user/flock2_ws/install/fiducial_vlam/lib/fiducial_vlam' ` Pondering into the file system, I couldnt find any references of vmap_node.

**Comment by clydemcqueen** [comment]
Ah, there's a bug in the launch files: they are referring to the older vlam node names. I will fix this.

**Comment by clydemcqueen** [comment]
Please take a look at the `clyde_fix_39` branch and PR and let me know if it solves your problem: https://github.com/clydemcqueen/flock2/pull/40
