### ISSUE TITLE
Tello CLI not sending commands

### ISSUE THREAD

**Issue by imsuneaik** [clydemcqueen/flock2#42]
I have been trying to run launch_two.py from flock2 to get both of the drones set up and running. I realised that I wasnt able to control the two drones from my VM, tello_driver does not send command and streamon commands at startup to initiate telemetry and video.
I have tried sending commands through ROS2 CLI  such as 

> `ros2 service call /tello_action tello_msgs/TelloAction "{cmd: 'takeoff'}"`
> `waiting for service to be available...`

Please advice. Thank you

**Comment by kadirou31** [comment]
Hi,
try this it works for me, i suppose that at least one drone is injected 'drone1' :
To takeoff :
ros2 service call /drone1/tello_action tello_msgs/TelloAction "{cmd: 'takeoff'}"
Drone turn
ros2 service call /drone1/tello_action tello_msgs/TelloAction "{cmd: 'rc 0 0 0 20'}"
hope that this will help

**Comment by imsuneaik** [comment]
Thanks for your inputs. I have tried your method but i was still facing the same issues. Can you please check if my configurations are correct. 

> I switched on one drone and forward udp packets from the drones through raspberry pi to my virtual machine.

> In VM, Using one terminal to run launch_two.py and another new tab of the CLI and calling the command ros2 service call /drone1/tello_action tello_msgs/TelloAction "{cmd: 'takeoff'}" 

I dont have an xbox gamepad so I am relying on the command line to send instructions to relay back to the drone. Thank you.

**Comment by kadirou31** [comment]
please execute this commands to display the exact name of your pub topics and  services : 
ros2 topic list
and 
ros2 service list

**Comment by imsuneaik** [comment]
Thank you it worked!
