### ISSUE TITLE
 fatal error: rclcpp_components/register_node_macro.hpp: No such file or directory  #include "rclcpp_components/register_node_macro.hpp"

### ISSUE THREAD

**Issue by Sail-Lab** [clydemcqueen/flock2#44]
UBUNTU 18.04 LTS
ROS2 ELOQUENT

When attempting to build with _colcon build_ this error is produced:

Starting >>> ros2_shared
Finished <<< ros2_shared [0.19s]                  
Starting >>> gscam
--- stderr: gscam                             
/home/USER/gscam2_ws/src/gscam2/src/subscriber_node.cpp:37:10: fatal error: rclcpp_components/register_node_macro.hpp: No such file or directory
 #include "rclcpp_components/register_node_macro.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/subscriber_node.dir/src/subscriber_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/subscriber_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
//opt/ros/eloquent/lib/libimage_transport.so: undefined reference to `message_filters::Connection::Connection(std::function<void ()> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [gscam_main] Error 1
make[1]: *** [CMakeFiles/gscam_main.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< gscam [0.47s, exited with code 2]

Summary: 1 package finished [0.80s]
  1 package failed: gscam
  1 package had stderr output: gscam

**Comment by clydemcqueen** [comment]
`ros-eloquent-rclcpp-components` must be installed.

This is required by `ros-eloquent-desktop`.
